# Generated by Django 3.2.6 on 2021-11-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20211130_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
